export const REMOVE_FROM_PINNED = 'REMOVE_FROM_PINNED';
export const ADD_TO_PINNED = 'ADD_TO_PINNED';
export const CHANGE_TO_INFO_PANEL = 'CHANGE_TO_INFO_PANEL';
export const CHANGE_TO_FAV_PANEL = 'CHANGE_TO_FAV_PANEL';
export const CHANGE_TO_SETTINGS_PANEL = 'CHANGE_TO_SETTINGS_PANEL';
